### ISSUE TITLE
[ENHANCEMENT] Decouple performance analyzer process from Opensearch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/docker-images#2]
Currently the opensearch docker container runs two process, opensearch and performance analyzer. See https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L108-L112. 
While this may work for us but as per the guidelines of docker official image project the recommendation is to have only one process per container, see https://github.com/docker-library/official-images#init. 

While we will be going ahead and creating a PR on docker official images repo with the current setup, creating this issue to track this improvement.

**Comment by sk-** [comment]
This would also reduce the memory footprint and startup times, which would be useful for running tests. On Github Actions we get every now and then an issue where the containers don't start and the culprit seems to always be OpenSearch.

It'd be great if the inclusion of the performance analyzer were controlled by a variable similar to `DISABLE_SECURITY_PLUGIN`. https://github.com/opensearch-project/docker-images/blob/e42b2cf0f9e7665a66d503f1e3cbd8ffae22e784/2.x/bin/opensearch-onetime-setup.sh#L39

**Comment by jbnjohnathan** [comment]
I think this issue was fixed in #9  as now there is such an option
https://github.com/opensearch-project/docker-images/blob/main/2.x/bin/opensearch-docker-entrypoint.sh#L57

**Comment by peterzhuamazon** [comment]
Close this issue.
As this has already been fixed.

We are currently not using this repo for docker images.

Here is the latest setup on docker for OpenSearch/Dashboards:
https://github.com/opensearch-project/opensearch-build/tree/main/docker

Thanks.
